<template>
  <section class="hero is-fullheight is-info" id="poll">
    <div style="height: 80px; overflow: hidden">
      <svg
        viewBox="0 0 500 80"
        preserveAspectRatio="none"
        style="
          height: 100%;
          width: 100%;
          -webkit-transform: scale(1);
          transform: scale(1);
        "
      >
        <path
          d="M-1.69,26.14 C265.79,93.25 271.49,-49.98 500.00,49.98 L500.00,0.00 L0.00,0.00 Z"
          fill="rgba(250, 240, 215, 1)"
        ></path>
      </svg>
    </div>
    <div
      class="hero-head has-text-centered observedElement section-title"
      style="padding-top: 0"
    >
      <div class="container">
        <h1 class="title is-size-2-mobile is-size-1-tablet is-uppercase">
          {{ $t("pages.mauritius.poll.title") }}
        </h1>
        <!-- <div class="box">
          <p class="block">{{ $t("pages.mauritius.poll.explications") }}</p>
        </div> -->
      </div>
    </div>
    <div class="hero-body observedElement section-body">
      <div class="container">
        <div class="columns is-centered">
          <div class="column is-7-tablet is-full-mobile">
            <div class="box explications observedElement section-body">
              <p class="block">
                {{ $t("pages.mauritius.poll.explications.first") }}
              </p>
              <p class="block">
                {{ $t("pages.mauritius.poll.explications.second") }} 😉
              </p>
            </div>
          </div>
        </div>
        <div class="columns is-centered">
          <div class="column is-5-tablet is-12-mobile">
            <form v-on:submit.prevent="add">
              <label class="label has-text-white">{{
                $t("pages.mauritius.poll.form.label")
              }}</label>
              <div class="field">
                <p class="control is-expanded">
                  <input
                    class="input is-success"
                    type="text"
                    :placeholder="$t('pages.mauritius.poll.form.placeholder')"
                    v-model="text.text"
                  />
                </p>
              </div>
              <div class="field">
                <p class="control">
                  <button type="submit" class="button is-success">
                    {{ $t("pages.mauritius.poll.form.submit") }}
                  </button>
                </p>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->

    <div style="height: 150px; overflow: hidden">
      <svg
        viewBox="0 0 500 150"
        preserveAspectRatio="none"
        style="height: 100%; width: 100%"
      >
        <path
          d="M-2.82,136.67 C149.99,150.00 435.10,108.05 506.20,122.86 L500.00,150.00 L0.00,150.00 Z"
          style="stroke: none; fill: #f5f5f5"
        ></path>
      </svg>
    </div>
  </section>
</template>

<script>
import { db } from "~/plugins/firebase.js";

let namesRef = db.ref("names");

export default {
  name: "app",
  firebase: { texts: namesRef },
  data() {
    return {
      text: {
        text: "",
      },
    };
  },
  methods: {
    add() {
      if (this.text.text !== "") {
        namesRef.push(this.text);
        this.text.text = "";
      }
    },
  },
};
</script>